name: voicerecorderapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  flutter_sound_lite: 8.3.12
  permission_handler: 8.1.6
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

